Feature/client base
gBenkyous/inTime pull request #51
Opened 2023-05-29 14:07 UTC by honmaharuki

2023-05-29 14:32 UTC, doranko requested changes

2023-05-29 14:32 UTC, doranko commented on client/app/README.md
> +dockerで開いている場合3000ではなく80ポートが割り当てられているため[http://localhost:80](http://localhost:80)で開いてください。
この説明はdocker-compose.ymlを見れば自明のため不要かと思います。
本説明が必要だと判断される場合はコメントでの説明ではなくdocker composeの基礎知識習得を前提に運用すべきと考えます。
また、http通信で80番ポートに繋ぐ場合は ":80" の記載は不要ではないでしょうか？

2023-05-29 14:42 UTC, doranko approved these changes, later dismissed

2023-05-29 14:42 UTC, doranko commented on client/app/tsconfig.json
> +    "checkJs": false // checkJsとは、.jsファイルの型チェックを行うかどうかを指定するオプションです。
型チェックを無効にしている理由はございますか？

2023-05-29 14:45 UTC, doranko commented on client/app/tsconfig.json
> +    "checkJs": false // checkJsとは、.jsファイルの型チェックを行うかどうかを指定するオプションです。
型チェックを無効にしている理由はございますか？

2023-05-30 15:09 UTC, honmaharuki commented on client/app/README.md
> +dockerで開いている場合3000ではなく80ポートが割り当てられているため[http://localhost:80](http://localhost:80)で開いてください。
> http通信で80番ポートに繋ぐ場合は ":80" の記載は不要ではないでしょうか？

この部分確かに要らなそうですね。
消しておきます！

>本説明が必要だと判断される場合はコメントでの説明ではなくdocker composeの基礎知識習得を前提に運用すべきと考えます。

これは少し難しいなと思っている点なのですが、docker composeの基礎知識習得を前提に運用するのが確かに正しいと思っています。
ただ、inTimeの場合、習得する知識がreact,go,dockerその他多岐にわたり習得する内容が多くなるかと思っています。
そのため知識の習得が追い付かず、なんかよくわからないけど動いているという状態になる可能性があるかもしれません。
その状態を避けるため細かいコメントを挟むことでこの部分はこんな風に動くんだ、ここってこんな派生もあるんだとしれるような状態にしておくのも勉強会といううえではよいのではないかと考えています。
（前提としてコメントを書く側が負担になるような細かい内容はどうかと思いますが、追加知識や派生知識でソースが汚れる程度であれば問題ないかと思っています。）

2023-05-30 15:11 UTC, honmaharuki commented on client/app/README.md
> +dockerで開いている場合3000ではなく80ポートが割り当てられているため[http://localhost:80](http://localhost:80)で開いてください。
一応、転職活動時に見せれるようなソースでありたいなという気持ちもあるので、業務で使うようなきれいなソースにしておきたいという気持ちもあります。
そのため余計に難しい部分だなと思っています。

2023-05-30 15:19 UTC, honmaharuki commented on client/app/tsconfig.json
> +    "checkJs": false // checkJsとは、.jsファイルの型チェックを行うかどうかを指定するオプションです。
こちらはjsからtsxに直す際に一部エラーが出ていた時の名残ですね。。。
errorを直すために追加して消し忘れていました。
今確認したらそれがなくてもエラーが出ていなかったので削除しておきます！

2023-05-30 15:19 UTC, honmaharuki commented on client/app/tsconfig.json
> +    "checkJs": false // checkJsとは、.jsファイルの型チェックを行うかどうかを指定するオプションです。
というか、trueにしておきます！

2023-05-30 15:22 UTC, honmaharuki commented
今回のやつ指摘はいらないと思ったらソースちゃんとレビューされててうれしい気持ちになりました。まる

2023-05-31 05:54 UTC, doranko commented on client/app/README.md
> +dockerで開いている場合3000ではなく80ポートが割り当てられているため[http://localhost:80](http://localhost:80)で開いてください。
@honmaharuki 
知識習得を助ける目的ということであればコメント残しておく方向で良いと思います！
ただ、せっかく記載するのであれば下記のような形で「どこでその設定がされているのか？」という情報も与えてあげた方が情報の検索もしやすく目的に即しているのではと思いますがいかがでしょうか？

> dockerで開いている場合は docker-compose.yml の client の ports 設定により、ローカルホストの 80 番とコンテナの 3000 番が繋がっているので [http://localhost:80](http://localhost:80) で開いてください。

2023-06-03 07:20 UTC, honmaharuki commented on client/app/README.md
> +dockerで開いている場合3000ではなく80ポートが割り当てられているため[http://localhost:80](http://localhost:80)で開いてください。
そっちの説明のほうがめちゃいいですね！！！
そっちにしましょう！！！

2023-06-03 07:30 UTC, doranko approved these changes

2023-06-17 01:33 UTC, merged