inTime #53_サーバ側 - ログの導入②（最新ブランチに対して）
gBenkyous/inTime pull request #59
Opened 2023-07-07 13:47 UTC by gonzaresu-sengoku

最新ブランチに対してzlogを導入しました！

トレースログの追加に関しては以下issueで行う予定
[サーバ側 - ログの導入③（トレースログの追加）](https://github.com/gBenkyous/inTime/issues/54)

2023-07-08 10:55 UTC, doranko requested changes

2023-07-08 10:55 UTC, doranko commented on server/config/config_staging.go
> +	LOG_FILE_NAME = "./test.log"
相対パスはミスを起こしやすいので絶対パス指定のほうが良いかと思いますが如何でしょうか。
また、TODO ということですが決定を先延ばしにする必要はないかと思いますので本レビュー中に議論・決定してしまってよいと思います。

2023-07-08 10:55 UTC, doranko commented on server/pkg/zlog/zlog.go
> +	// ファイル出力先指定
本コメントの記載位置としては一つ下が適切かと思います。

```go
zlog := zerolog.Nop()
// ファイル出力先設定
file, err := os.OpenFile(config.LOG_FILE_NAME, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
```

また出力先を指定しているのは `config.LOG_FILE_NAME` であり、それについては config_staging.go でコメント記載されているので本コメント自体不要に思います。

2023-07-08 10:55 UTC, doranko commented on server/pkg/zlog/zlog.go
> +	}
Trace, Debug, Info, Warn, Error, Fatal, Panic それぞれについて最終行以外同じ処理のようですので、同じ処理を記述している部分はロガーを取得するメソッドとして切り出してください。

また本メソッド群を利用した場合は毎回ファイルを開く処理が入るかと思いますので下記点について議論いただきますようお願いいたします。

- ファイル開閉操作がアプリ動作に影響を与えない範囲に収まるか？
- アプリ全体で一つのロガーオブジェクトを共有するような方法はないか？
  - ログファイルを「開く」処理をアプリ起動時の1回だけにできないか？
- (おまけ) 日付単位でログローテーションできないか？
  - lumberjack パッケージを利用すればファイルサイズでのローテーションはできそうだが日付単位のローテーション設定はみつけられなかった
  - パッケージが見つからなくても自前実装は難しくなさそう
    - 毎回ファイルを開く処理から始めるのであればファイル名に日付をくっ付けてしまう
    - アプリ起動時に1度だけファイルを開く処理をできるのであれば、書き込み時にファイルの作成日or更新日を取得して現在日と異なるのであれば書き込み前に開きなおす
    など

2023-07-08 10:55 UTC, doranko commented on server/pkg/zlog/zlog.go
> +	file, err := os.OpenFile(config.LOG_FILE_NAME, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
ファイルを開いた後に close していないようですが `defer file.close()` とすると何か不具合が起きますでしょうか？

2023-07-13 17:42 UTC, haruki256 commented on server/config/config_staging.go
> +	LOG_FILE_NAME = "./test.log"
僕は個人的には絶対パス指定で問題ないかと思っています。

2023-07-17 15:24 UTC, haruki256 commented
ログの出力名を残しておくと後から見たときわかりやすいかも！
redmeでもどこでもコメントとかでもいいけど、なんのログでどんな情報が入っているのかとか、
まあ、wikiのほうに残しておく感じでもいいけど！

2023-07-22 01:07 UTC, gonzaresu-sengoku commented on server/pkg/zlog/zlog.go
> +	file, err := os.OpenFile(config.LOG_FILE_NAME, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
ありがとうございます！！確認します！！

2023-07-29 02:13 UTC, watabusi commented on server/pkg/zlog/zlog.go
> +	}
方針とソース参考について https://github.com/gBenkyous/inTime/issues/67

2023-07-29 02:35 UTC, watabusi commented on server/config/config_staging.go
> +	LOG_FILE_NAME = "./test.log"
方針 https://github.com/gBenkyous/inTime/issues/66

2024-01-13 00:38 UTC, honmaharuki commented
https://github.com/gBenkyous/inTime/pull/89/files
上記プルリクがあるためこのプルリクが不要であればクローズ予定

2024-01-27 00:20 UTC, closed without merging