Feature/client/base moc
gBenkyous/inTime pull request #91
Opened 2023-11-19 00:22 UTC by honmaharuki

2023-11-19 00:37 UTC, doranko commented
mockの追加ではなく、ルーティングの修正とのこと

2023-11-19 02:20 UTC, doranko requested changes

2023-11-19 02:20 UTC, doranko commented on client/app/src/pages/moc/Moc/Hero/index.tsx
> +    width: ${theme.spacing(8)};
この辺りは共通部品として抜き出したいですね

2023-11-19 02:20 UTC, doranko commented on client/app/src/routes/applicationRoutes.tsx
> +export const applicationRoutes = [
routerの名称についてルール決めをお願いします（URLの親部分の名前 or 対象のコンポーネントが含まれるディレクトリ名 or ... etc.）

2023-11-19 02:20 UTC, doranko commented on client/app/docs/manual.md
> +router.tsxにルーティングを記述する
routes 配下に細分化して実装する方針にするのであれば、そのように修正お願いします。

2023-11-19 02:20 UTC, doranko commented on client/app/docs/architecture.md
> +│   ├── router.tsx            # アプリケーションのルーティングを管理
routes 配下に細分化して実装する方針にするのであれば、そのように修正お願いします。

2023-11-19 02:20 UTC, doranko commented on client/app/src/router.tsx
routes配下で細分化して管理するのであれば本ファイルは不要では無いでしょうか？

2023-11-19 03:52 UTC, honmaharuki commented
確認した結果足りない部分が多そうだったので一旦修正かまします。

2023-11-19 04:31 UTC, honmaharuki commented on client/app/src/routes/applicationRoutes.tsx
> +export const applicationRoutes = [
[pagesカテゴリ名]Routesとしようと考えています。
イメージとして
pages/moc/MocLogin
pages/moc/MocHome
とあるならば、
routes/mocRoutesを作成するイメージです。
アーキテクチャ図と、マニュアルに記載しておきます。

2023-11-19 04:35 UTC, honmaharuki commented
現状のページ設定に合わせて、ルーティングをしておりますが、今後ページを作る際には、pages配下にページのメインビューとなるコンポーネントを配置していきたいと考えています。

2023-11-19 06:54 UTC, doranko commented on client/app/src/pages/moc/Moc/Hero/index.tsx
実装が進んだら削除されるのでいいと言えばいいのですが、`moc` ではなく `mock` です。

2024-02-16 23:51 UTC, honmaharuki commented
開発完了のためレビュー依頼予定

2024-02-17 01:06 UTC, doranko approved these changes

2024-02-17 01:20 UTC, merged