Feature/client/run on save
gBenkyous/inTime pull request #94
Opened 2023-12-09 03:37 UTC by watabusi

VSC拡張機能のRun on Save追加

各々で必要な設定：settings.jsonの設定
・vsc上でctrl+shift+Pでコマンドパレット開く
・「設定」を入力、「基本設定：ユーザ設定を開く(JSON)」選択
・以下を追記
```
"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "*.tsx",
                "cmd": "yarn install"
            }
        ]
    }
```

2023-12-11 02:54 UTC, doranko commented
@watabusi 
1. プルリクの向き先は dev_v0.0.1 が適当では無いでしょうか？（凄い差分が出てる。。。）
2. settings.json は `client/.vscode/settings.json` として用意することで個別に設定する必要はなくなるかと思います（その場合 `client/app` 配下に `.vscode` を配置するか、`client` 直下に `.vscode` を配置して docker-compose.yml を追記するかどちらかになると思います）

2023-12-11 03:08 UTC, watabusi commented
@doranko 
ありがとうございます！！あとで編集します！！！

2023-12-12 12:25 UTC, doranko requested changes
https://github.com/gBenkyous/inTime/pull/95

2024-01-27 00:27 UTC, doranko approved these changes

2024-02-17 00:18 UTC, merged